name: contribution-streak-maintainer

on:
  schedule:
    - cron: "0 22 * * *" # Runs every day at 10:00 PM UTC
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

jobs:
  contribution-streak-maintainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # Checks out your repository code

      - name: Install dependencies
        run: npm install contribution-streak-maintainer # Install npm package

      - name: Make a contribution
        run: npx contribution-streak-maintainer ${{github.repository}} --email=tech.vishalkrsingh@gmail.com
        env:
          DEVFUL_GITHUB_TOKEN: ${{ secrets.CSM_GITHUB_TOKEN }} # Use your GitHub secret token
